// frontend/vue-nuxtjs/components/LoginButton.vue
<template>
  <OCButton @click="handleLogin">Connect OCID</OCButton>
</template>

<script>
import { useOCAuth } from "@opencampus/ocid-connect-js";
import OCButton from "./OCButton.vue";

export default {
  name: 'LoginButton',
  components: {
    OCButton
  },
  setup() {
    const { ocAuth } = useOCAuth();

    const handleLogin = async () => {
      await ocAuth.signInWithRedirect({
        state: "opencampus",
      });
    };

    return {
      handleLogin
    };
  }
}
</script>

// frontend/react-nextjs/components/LoginButton.tsx
"use client";
import { useOCAuth } from "@opencampus/ocid-connect-js";
import OCButton from "./OCButton";
import { usePathname } from "next/navigation";

const LoginButton = () => {
  const { ocAuth } = useOCAuth();
  const pathname = usePathname();

  const handleLogin = async () => {
    try {
      localStorage.setItem("previousPath", pathname);

      await ocAuth.signInWithRedirect({
        state: "opencampus",
      });
    } catch (error) {
      console.error("Error initiating login:", error);
    }
  };

  return <OCButton onClick={handleLogin}>Connect OCID</OCButton>;
};

export default LoginButton;
