// frontend/vue-nuxtjs/pages/anonymous-feedback-dapp/index.vue
<template>
  <div class="App min-h-screen flex flex-col items-center justify-between">
    <Header />
    <div class="flex flex-col items-center justify-center flex-grow w-full mt-24 px-4">
      <Card class="w-full max-w-2xl p-8 shadow-lg">
        <CardHeader>
          <CardTitle class="text-center text-4xl font-bold mt-4">
            📚 Anonymous FB Dapp 📚
          </CardTitle>
        </CardHeader>
        <CardContent class="flex flex-col items-center mt-4 space-y-6">
          <LoginButton v-if="!ocidUsername" />
          <div v-if="ocidUsername" class="text-center text-xl">
            <h1>
              👉Welcome, 
              <NuxtLink to="/user">
                <strong>{{ ocidUsername }}</strong>
              </NuxtLink>👈
            </h1>
          </div>
          <div v-if="isConnected" class="text-center text-xl">
            <h1>
              Connected to wallet address: <strong>{{ accountAddress }}</strong>
            </h1>
          </div>
          <Button
            v-if="!isConnected"
            class="bg-teal-400 hover:bg-teal-700 text-black font-bold py-2 px-4 rounded-md mb-4"
            @click="connectWallet"
            variant="link"
          >
            Connect with MetaMask
          </Button>
          <div class="flex flex-col items-center w-full">
            <Textarea
              v-model="feedback"
              placeholder="Enter your anonymous feedback about the course here"
              class="w-full mb-4"
            />
            <Button
              class="bg-teal-300 hover:bg-teal-700 text-black font-bold py-1 px-6 rounded"
              @click="isConnected ? submitFeedback : undefined"
            >
              Submit Feedback
            </Button>
            <Button
              v-if="isEducator"
              class="bg-teal-300 hover:bg-teal-700 text-black font-bold py-1 px-6 rounded mt-4"
              @click="isConnected ? getFeedback : undefined"
            >
              View Feedback
            </Button>
            <div v-if="showMessage">
              <p class="text-center text-sm mt-6">loading...</p>
              <p class="mt-4 text-xs">
                Txn hash: 
                <a
                  class="text-teal-300"
                  :href="'https://opencampus-codex.blockscout.com/tx/' + txnHash"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {{ txnHash }}
                </a>
              </p>
              <p class="mt-2 text-xs">
                Please wait till the Txn is completed :)
              </p>
            </div>
          </div>
          <div v-if="isEducator && submittedFeedback.length > 0" class="w-full mt-8">
            <h2 class="text-2xl font-bold mb-4">Submitted Feedback:</h2>
            <div
              v-for="(feedback, index) in submittedFeedback"
              :key="index"
              class="bg-gray-100 p-4 rounded-md mb-2"
            >
              {{ feedback }}
            </div>
          </div>
          <Alert v-if="!isEducator" class="mt-4">
            <AlertCircle class="h-4 w-4" />
            <AlertTitle>Student View</AlertTitle>
            <AlertDescription>
              As a student, you can submit anonymous feedbacks about the
              courses but cannot view all feedback submissions, only
              educators with ocid (edu_) can see it.
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    </div>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useOCAuth } from "@opencampus/ocid-connect-js"
import { jwtDecode } from "jwt-decode"
import Web3 from 'web3'
import contractJson from "@/contracts/AnonymousFeedback.sol/AnonymousFeedback.json"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertCircle } from "lucide-vue-next"
import Header from "@/components/Header.vue"
import Footer from "@/components/Footer.vue"
import LoginButton from "@/components/LoginButton.vue"
import type { DecodedToken, Contracts } from "@/types"

const contractAddress = "0x5E953eF799f59D2589b72c19c05A7e02EAbcdf0C"

const { authState } = useOCAuth()
const mmStatus = ref("Not connected!")
const isConnected = ref(false)
const accountAddress = ref<string | undefined>(undefined)
const feedback = ref("")
const submittedFeedback = ref<string[]>([])
const web3 = ref<Web3 | undefined>(undefined)
const getNetwork = ref<number | undefined>(undefined)
const contracts = ref<Contracts | undefined>(undefined)
const loading = ref(false)
const txnHash = ref<string | null>(null)
const showMessage = ref(false)
const ocidUsername = ref<string | null>(null)
const isEducator = ref(false)

const switchToOpenCampusNetwork = async () => {
  if (typeof window.ethereum !== "undefined") {
    try {
      await window.ethereum.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: "0xa045c" }],
      })
    } catch (switchError: any) {
      if (switchError.code === 4902) {
        try {
          await window.ethereum.request({
            method: "wallet_addEthereumChain",
            params: [
              {
                chainId: "0xa045c",
                chainName: "Open Campus Codex",
                nativeCurrency: {
                  name: "EDU",
                  symbol: "EDU",
                  decimals: 18,
                },
                rpcUrls: ["https://rpc.open-campus-codex.gelato.digital"],
                blockExplorerUrls: [
                  "https://opencampus-codex.blockscout.com/",
                ],
              },
            ],
          })
        } catch (addError) {
          console.error("Failed to add Open Campus Codex network:", addError)
        }
      } else {
        console.error(
          "Failed to switch to Open Campus Codex network:",
          switchError
        )
      }
    }
  }
}

const connectWallet = async () => {
  if (typeof window.ethereum !== "undefined") {
    try {
      await switchToOpenCampusNetwork()
      const chainId = await window.ethereum.request({
        method: "eth_chainId",
      })

      if (chainId !== "0xa045c") {
        alert("Please connect to the Open Campus Codex network in MetaMask.")
        return
      }

      await window.ethereum.request({ method: "eth_requestAccounts" })
      const accounts = await window.ethereum.request({
        method: "eth_accounts",
      })
      accountAddress.value = accounts[0]
      mmStatus.value = "Connected!"
      isConnected.value = true
    } catch (error) {
      console.error("Failed to connect to wallet:", error)
    }
  } else {
    alert("Please install MetaMask!")
  }
}

onMounted(async () => {
  if (authState.value.idToken) {
    const decodedToken = jwtDecode<DecodedToken>(authState.value.idToken)
    ocidUsername.value = decodedToken.edu_username
    isEducator.value = decodedToken.edu_username.startsWith("edu_")
  }

  try {
    if (typeof window.ethereum !== "undefined") {
      const web3Instance = new Web3(window.ethereum)
      web3.value = web3Instance
      const networkId: any = await web3Instance.eth.getChainId()
      getNetwork.value = networkId
      const AnonymousFeedback = new web3Instance.eth.Contract(
        contractJson.abi,
        contractAddress
      ) as Contracts
      contracts.value = AnonymousFeedback
      AnonymousFeedback.setProvider(window.ethereum)
    } else {
      alert("Please install MetaMask!")
    }
  } catch (error) {
    console.error("Failed to initialize web3 or contract:", error)
  }
})

const submitFeedback = async () => {
  if (!feedback.value.trim()) {
    alert("Feedback cannot be empty.")
    return
  }
  loading.value = true
  showMessage.value = true
  if (contracts.value && accountAddress.value) {
    try {
      await contracts.value.methods
        .submitFeedback(feedback.value)
        .send({ from: accountAddress.value })
        .on("transactionHash", (hash: string) => {
          txnHash.value = hash
        })
      feedback.value = ""
      alert("Feedback submitted successfully!")
    } catch (error) {
      console.error("Failed to submit feedback:", error)
    }
  }
  loading.value = false
  setTimeout(() => {
    showMessage.value = false
  }, 3000)
}

const getFeedback = async () => {
  if (contracts.value) {
    try {
      const feedbackList = await contracts.value.methods.getAllFeedback().call()
      submittedFeedback.value = feedbackList
    } catch (error) {
      console.error("Failed to get feedback:", error)
    }
  }
}
</script>

// frontend/vite-remixjs/app/routes/anonymous-feedback-dapp.tsx
import React, { useState, useEffect } from "react";
import Web3 from "web3";
import contractJson from "~/contracts/AnonymousFeedback.sol/AnonymousFeedback.json";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Button } from "~/components/ui/button";
import { Textarea } from "~/components/ui/textarea";
import LoginButton from "~/components/LoginButton";
import { useOCAuth } from "@opencampus/ocid-connect-js";
import { jwtDecode } from "jwt-decode";
import Header from "~/components/Header";
import Footer from "~/components/Footer";
import { MetaMaskConnect } from "~/components/MetaMaskConnect";
import ClientOnly from "~/components/ClientOnly";

interface Contracts {
  methods: {
    submitFeedback: (feedback: string) => {
      send: (options: { from: string }) => Promise<any>;
    };
    getAllFeedback: () => {
      call: () => Promise<string[]>;
    };
  };
  setProvider: (provider: any) => void;
}

interface DecodedToken {
  edu_username: string;
  [key: string]: any;
}

export default function FeedbackApp() {
  const { authState } = useOCAuth();
  const [feedback, setFeedback] = useState<string>("");
  const [submittedFeedback, setSubmittedFeedback] = useState<string[]>([]);
  const [web3, setWeb3] = useState<Web3 | undefined>(undefined);
  const [contracts, setContracts] = useState<Contracts | undefined>(undefined);
  const [loading, setLoading] = useState<boolean>(false);
  const [txnHash, setTxnHash] = useState<string | null>(null);
  const [showMessage, setShowMessage] = useState<boolean>(false);
  const [ocidUsername, setOcidUsername] = useState<string | null>(null);
  const [isEducator, setIsEducator] = useState<boolean>(false);
  const [accountAddress, setAccountAddress] = useState<string | undefined>(
    undefined
  );
  const [isConnected, setIsConnected] = useState<boolean>(false);

  useEffect(() => {
    if (authState.idToken) {
      try {
        const decodedToken = jwtDecode<DecodedToken>(authState.idToken);
        setOcidUsername(decodedToken.edu_username);

        setIsEducator(decodedToken.edu_username.startsWith("edu_"));
      } catch (error) {
        console.error("Failed to decode token:", error);
      }
    }
  }, [authState.idToken]);

  const handleConnect = async (address: string) => {
    try {
      const web3Instance = new Web3(window.ethereum);
      setWeb3(web3Instance);
      setAccountAddress(address);
      setIsConnected(true);

      const contractAddress = "0x1f99874fa16F5228b518e475CaF29d340BbA403f";
      const AnonymousFeedback = new web3Instance.eth.Contract(
        contractJson.abi,
        contractAddress
      ) as unknown as Contracts;
      AnonymousFeedback.setProvider(window.ethereum);
      setContracts(AnonymousFeedback);
    } catch (error) {
      console.error("Failed to initialize web3 or contract:", error);
    }
  };

  const handleDisconnect = () => {
    setWeb3(undefined);
    setContracts(undefined);
    setAccountAddress(undefined);
    setIsConnected(false);
    setSubmittedFeedback([]);
  };

  const submitFeedback = async () => {
    if (!feedback.trim()) {
      alert("Feedback cannot be empty.");
      return;
    }
    setLoading(true);
    setShowMessage(true);
    if (contracts && accountAddress) {
      try {
        const transaction = await contracts.methods
          .submitFeedback(feedback)
          .send({ from: accountAddress });

        if (transaction.transactionHash) {
          setTxnHash(transaction.transactionHash);
        }

        setFeedback("");
        alert("Feedback submitted successfully!");
      } catch (error) {
        console.error("Failed to submit feedback:", error);
      }
    }
    setLoading(false);
    setTimeout(() => {
      setShowMessage(false);
    }, 3000);
  };

  const getFeedback = async () => {
    if (contracts) {
      try {
        const feedback = await contracts.methods.getAllFeedback().call();
        setSubmittedFeedback(feedback);
      } catch (error) {
        console.error("Failed to get feedback:", error);
      }
    }
  };

  return (
    <div className="App min-h-screen flex flex-col items-center justify-between">
      <Header />
      <div className="flex flex-col items-center justify-center flex-grow w-full mt-24 px-4">
        <Card className="w-full max-w-2xl p-8 shadow-lg">
          <CardHeader>
            <CardTitle className="text-center text-4xl font-bold mt-4">
              📚 Anonymous FB Dapp 📚
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center mt-4 space-y-6">
            {!ocidUsername && <LoginButton />}
            {ocidUsername && (
              <div className="text-center text-xl">
                <h1>
                  👉Welcome,{" "}
                  <a href="/user">
                    <strong>{ocidUsername}👈</strong>
                  </a>{" "}
                </h1>
              </div>
            )}

            <ClientOnly fallback={<div>Loading wallet connection...</div>}>
              <MetaMaskConnect
                onConnect={handleConnect}
                onDisconnect={handleDisconnect}
              />

              {isConnected && (
                <div className="flex flex-col items-center w-full">
                  <Textarea
                    placeholder="Enter your anonymous feedback about the course here"
                    value={feedback}
                    onChange={(e) => setFeedback(e.target.value)}
                    className="w-full mb-4"
                  />
                  <Button
                    className="bg-teal-300 hover:bg-teal-700 text-black font-bold py-1 px-6 rounded"
                    onClick={submitFeedback}
                  >
                    Submit Feedback
                  </Button>
                  {isEducator && (
                    <>
                      <Button
                        className="bg-teal-300 hover:bg-teal-700 text-black font-bold py-1 px-6 rounded mt-4"
                        onClick={getFeedback}
                      >
                        View Feedback
                      </Button>
                      {submittedFeedback.length > 0 && (
                        <div className="mt-4 w-full">
                          <h3 className="text-xl mb-2">Submitted Feedback:</h3>
                          {submittedFeedback.map((fb, index) => (
                            <div
                              key={index}
                              className="bg-gray-100 p-3 rounded mb-2"
                            >
                              {fb}
                            </div>
                          ))}
                        </div>
                      )}
                    </>
                  )}
                  {showMessage && (
                    <>
                      <p className="text-center text-sm mt-6">
                        Submitting feedback...
                      </p>
                      {txnHash && (
                        <p className="mt-2 text-xs">
                          Txn hash:{" "}
                          <a
                            className="text-teal-600"
                            href={
                              "https://educhain.blockscout.com/tx/" + txnHash
                            }
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            {txnHash}
                          </a>
                        </p>
                      )}
                    </>
                  )}
                </div>
              )}
            </ClientOnly>
          </CardContent>
        </Card>
      </div>
      <Footer />
    </div>
  );
}
