// frontend/vue-nuxtjs/components/LoginButton.vue
<template>
  <OCButton @click="handleLogin">Connect OCID</OCButton>
</template>

<script>
import { useOCAuth } from "@opencampus/ocid-connect-js";
import OCButton from "./OCButton.vue";

export default {
  name: 'LoginButton',
  components: {
    OCButton
  },
  setup() {
    const { ocAuth } = useOCAuth();

    const handleLogin = async () => {
      await ocAuth.signInWithRedirect({
        state: "opencampus",
      });
    };

    return {
      handleLogin
    };
  }
}
</script>

// frontend/react-remix/app/components/LoginButton.tsx
import { useOCAuth } from "@opencampus/ocid-connect-js";
import OCButton from "./OCButton";
import { useEffect } from "react";
import { useNavigate } from "@remix-run/react";

const LoginButton = () => {
  const { ocAuth } = useOCAuth();
  const navigate = useNavigate();

  const handleLogin = async () => {
    await ocAuth.signInWithRedirect({
      state: "opencampus",
    });
  };

  return <OCButton onClick={handleLogin}>Connect OCID</OCButton>;
};

export default LoginButton;
